### ISSUE TITLE
Create source ||| target phrase table 

### ISSUE THREAD

**Issue by mehmedes** [clab/fast_align#24]
Is it possible to convert the alignment output into a phrase table:

source ||| target
source ||| target
source ||| target

?

**Comment by john-hewitt** [comment]
That's outside the scope of the program. I'd suggest looking at an MT pipeline that can use FastAlign as part of the pipeline. Try [Moses](http://www.statmt.org/moses/) or [Apache Joshua](https://cwiki.apache.org/confluence/display/JOSHUA/Apache+Joshua+(Incubating)+Home)
