### ISSUE TITLE
Using fast_align to train save the model in infer.

### ISSUE THREAD

**Issue by Raghava14** [clab/fast_align#33]
Hello I have a large parallel corpus on which I used fast-align to get alignments  but I have a few other sentences which are different from the original corpus for which I need to get alignment info. Is there a way so that I can use the knowledge learnt from large parallel corpus to directly get alignments for the smaller set of sentences.(Similar to  saving checkpoint so that I can load checkpoint and get alignments).
Thanks in advance.

**Comment by ru1996** [comment]
Hi, there. I am facing the same situation. Did you have an answer?

**Comment by liesun1994** [comment]
Of course, you can use force_align.py !

**Comment by tomsbergmanis** [comment]
@liesun1994 can you please explain how? It isn't immediately clear to me...

**Comment by liesun1994** [comment]
First step, run: 
  `fast_align -i corpus.f-e -d -v -o -p fwd_params >fwd_align 2>fwd_err`
  `fast_align -i corpus.f-e -r -d -v -o -p rev_params >rev_align 2>rev_err`
where corpus.f-e is training corpus, fwd_prarams, fwd_err, rev_params, rev_err are the saved models. **Do not remove fwd_error and rev_error!** 

Second step:
run:
 `force_align.py fwd_params fwd_err rev_params rev_err [heuristic] <in.f-e >out.f-e.gdfa`

where heuristic is one of: (intersect union grow-diag grow-diag-final grow-diag-final-and) default=grow-diag-final-and , in.f-e is the file which you want to get alignment.

**Comment by liesun1994** [comment]
@ru1996

**Comment by liesun1994** [comment]
@Raghava14

**Comment by tomsbergmanis** [comment]
Thanks! Got it now!

**Comment by Raghava14** [comment]
Thanks @liesun1994  closing this for now !

**Comment by genbei** [comment]
> 第一步，运行：
> `fast_align -i corpus.f-e -d -v -o -p fwd_params >fwd_align 2>fwd_err`
> `fast_align -i corpus.f-e -r -d -v -o -p rev_params >rev_align 2>rev_err`
> corpus.fe是训练语料库，fwd_prarams，fwd_err，rev_params，rev_err是保存的模型。**不要删除fwd_error和rev_error！**
> 
> 第二步：
> 运行：
> `force_align.py fwd_params fwd_err rev_params rev_err [heuristic] <in.f-e >out.f-e.gdfa`
> 
> 其中启发式是以下项之一：（相交并列增长图生长增长图最终增长图最终和），in.fe是您要对齐的文件。



> 第一步，运行：
> `fast_align -i corpus.f-e -d -v -o -p fwd_params >fwd_align 2>fwd_err`
> `fast_align -i corpus.f-e -r -d -v -o -p rev_params >rev_align 2>rev_err`
> corpus.fe是训练语料库，fwd_prarams，fwd_err，rev_params，rev_err是保存的模型。**不要删除fwd_error和rev_error！**
> 
> 第二步：
> 运行：
> `force_align.py fwd_params fwd_err rev_params rev_err [heuristic] <in.f-e >out.f-e.gdfa`
> 
> 其中启发式是以下项之一：（相交并列增长图生长增长图最终增长图最终和），in.fe是您要对齐的文件。



> First step, run:
> `fast_align -i corpus.f-e -d -v -o -p fwd_params >fwd_align 2>fwd_err`
> `fast_align -i corpus.f-e -r -d -v -o -p rev_params >rev_align 2>rev_err`
> where corpus.f-e is training corpus, fwd_prarams, fwd_err, rev_params, rev_err are the saved models. **Do not remove fwd_error and rev_error!**
> 
> Second step:
> run:
> `force_align.py fwd_params fwd_err rev_params rev_err [heuristic] <in.f-e >out.f-e.gdfa`
> 
> where heuristic is one of: (intersect union grow-diag grow-diag-final grow-diag-final-and) default=grow-diag-final-and , in.f-e is the file which you want to get alignment.

my script is `fast_align -i train.en-zh -d -o -v > forward.align`
Error  is
fast_align：Command not found

why

**Comment by genbei** [comment]
> First step, run:
> `fast_align -i corpus.f-e -d -v -o -p fwd_params >fwd_align 2>fwd_err`
> `fast_align -i corpus.f-e -r -d -v -o -p rev_params >rev_align 2>rev_err`
> where corpus.f-e is training corpus, fwd_prarams, fwd_err, rev_params, rev_err are the saved models. **Do not remove fwd_error and rev_error!**
> 
> Second step:
> run:
> `force_align.py fwd_params fwd_err rev_params rev_err [heuristic] <in.f-e >out.f-e.gdfa`
> 
> where heuristic is one of: (intersect union grow-diag grow-diag-final grow-diag-final-and) default=grow-diag-final-and , in.f-e is the file which you want to get alignment.

my script is fast_align -i train.en-zh -d -o -v > forward.align
Error is
fast_align：Command not found

why

**Comment by sugeeth14** [comment]
@genbei  Follow the steps to install `fast_align` first available [here](https://github.com/clab/fast_align#compiling-and-using-fast_align)

**Comment by zolastro** [comment]
I would like to point out that if you want to run this using python 3.x, you should check [ttwelve12's solution](https://github.com/clab/fast_align/issues/58#issuecomment-851889247).
