### ISSUE TITLE
Can't read input file...

### ISSUE THREAD

**Issue by mohammedayub44** [clab/fast_align#35]
Hi,

I'm trying to run the fast align on UN parallel dataset. I have tokenized it and running the below command:

`./fast_align -i /home/ubuntu/mayub/datasets/raw/un/fastalign_input.txt -d -o -v > /home/ubuntu/mayub/datasets/raw/un/forward_align_en_es.align`

it runs for a while with the below output and gives error on Iteration 2: saying it cant read the input file.

![image](https://user-images.githubusercontent.com/7122670/48432977-ec6a1380-e743-11e8-8df5-8069047d07b8.png)

![image](https://user-images.githubusercontent.com/7122670/48432948-d8261680-e743-11e8-9d0f-b6b07908686b.png)

Any idea why it is failing ? looping some folks for help. @armatthews @mjdenkowski 

Thanks !

Mohammed Ayub

**Comment by mohammedayub44** [comment]
This was just session timing out.

**Comment by yugaljain1999** [comment]
@mohammedayub44 Can u tell how did you generated tokenized input text file?
Thanks
