### ISSUE TITLE
How many iterations does it run and ETA ?

### ISSUE THREAD

**Issue by mohammedayub44** [clab/fast_align#36]
Hi,

How many iterations does it run  ? 
Any idea how long does this take to run finish on a t2.xlarge instance ?
@armatthews 

Thanks !

Mohammed Ayub

**Comment by mohammedayub44** [comment]
Kinda figured it out going through the code base, I think it runs 5 iterations by default. Takes about 10-12 min /iteration on a t2.xlarge machine.

Mohammed Ayub

**Comment by Ryanight** [comment]
I have problem with larger dataset while using ./fast_align
I found that I could not deal with the data more than 1000 lines maybe. Have you ever met the same problem or how do you usually run the script?
For me it is: 
./fast_align -i ~/sockeye_autopilot/systems/wmt14_en_de/data/bpe/new_combined_srctrgaa -d -o -v > forward.align_endea
Thanks a lot!

**Comment by mohammedayub44** [comment]
@Ryanight I have no problem running files with more than 1000 lines. Maybe the input file has some problems. I have created the input file and the running the commands like below:

create the input file:

`pr -mtJS' ||| ' /home/ubuntu/mayub/datasets/train_tokenized_bpe_applied.en /home/ubuntu/mayub/datasets/train_tokenized_bpe_applied.es > /home/ubuntu/mayub/datasets/fastalign_input_en_es.txt`

forward train:
`fast_align/build/fast_align -i /home/ubuntu/mayub/datasets/fastalign_input_en_es.txt -d -o -v > /home/ubuntu/mayub/datasets/forward_align_en_es.align`

reverse train:
`fast_align/build/fast_align -i /home/ubuntu/mayub/datasets/fastalign_input_en_es.txt -d -o -v -r > /home/ubuntu/mayub/datasets/reverse_align_en_es.align`

symmetrize:
`fast_align/build/atools -i /home/ubuntu/mayub/datasets/forward_align_en_es.align -j /home/ubuntu/mayub/datasets/reverse_align_en_es.align -c grow-diag-final-and > /home/ubuntu/mayub/datasets/corpus_en_es.gdfa`
