### ISSUE TITLE
Problem with large data 

### ISSUE THREAD

**Issue by Ryanight** [clab/fast_align#41]
I have problem with larger dataset while using ./fast_align
I found that I could not deal with the data more than 1000 lines maybe. Have you ever met the same problem or how do you usually run the script?
For me it is:
./fast_align -i ~/sockeye_autopilot/systems/wmt14_en_de/data/bpe/new_combined_srctrgaa -d -o -v > forward.align_endea
Thanks a lot!

**Comment by spate141** [comment]
I think this depends on memory. Last time when I tried to use corpus with about ~30M sentences, `fast_align` crashed because of out of memory error. Then I tried with 10M sentences and it was using about 23GB of memory. I'm not sure if there's any other way around this. If yes, I would also like to know!

**Comment by Ryanight** [comment]
Thanks!
Yea, memory does make sense! But it does not give me any information about the error. Actually the fast_align finish its process only with the same lines of blank. I have no idea about what is happening. But still, I succeeded on the data below 100 lines.

**Comment by Ryanight** [comment]
@spate141 
Hi, I have tried again with 26GB memory linux computer. There is no error print out instead of `"Error in line 810000"`. I do think this kind of error does not matter, right?
At the end of the procession, I found that information:
```
  log_e likelihood: nan
  log_2 likelihood: nan
     cross entropy: -nan
        perplexity: -nan
      posterior p0: 0
 posterior al-feat: 0
       size counts: 14490
```
The `"nan"` there may showing some problems. But I still have no idea about that.

**Comment by spate141** [comment]
"Error in line 810000" means, that line is either blank or has some issue; either in source or target side. I would recommend to clean your data before using it with fast_align

**Comment by Ryanight** [comment]
> "Error in line 810000" means, that line is either blank or has some issue; either in source or target side. I would recommend to clean your data before using it with fast_align
@spate141 Thanks! I think the problem has been solved by this way.
