### ISSUE TITLE
en-jap alignements 

### ISSUE THREAD

**Issue by ZordoC** [clab/fast_align#47]
Hello! 
I'm having troubles aligning a en-jap file. I've seen online people mention using fast align on japanese, couldn't find any guidance tho! Has anyone tried it out?  

`ARG=i
ARG=d
ARG=o
ARG=v
INITIAL PASS
Error in line 1
Select a file to blacklist||| 除外 リスト に 追加 する ファイル を 選択
Error in line 2
Clear Usage Data||| 利用 履歴 データ を クリア
Error in line 3
Delete records of which files and applications were used:||| ファイル と アプリケーション を 利用 し た 記録 の 削除 :
Error in line 4
In the past hour||| 1 時間 以内
expected target length = source length * 0
ITERATION 1
Error in line 4
Select a file to blacklist||| 除外 リスト に 追加 する ファイル を 選択
Error in line 4
Clear Usage Data||| 利用 履歴 データ を クリア
Error in line 4
In the past hour||| 1 時間 以内
Error in line 4
Delete records of which files and applications were used:||| ファイル と アプリケーション を 利用 し た 記録 の 削除 :
  log_e likelihood: 0
  log_2 likelihood: 0
     cross entropy: -nan
        perplexity: -nan
      posterior p0: -nan
 posterior al-feat: -nan
       size counts: 4
ITERATION 2
Error in line 4
In the past hour||| 1 時間 以内
Error in line Error in line 4
Delete records of which files and applications were used:||| ファイル と アプリケーション を 利用 し た 記録 の 削除 :
4
Select a file to blacklist||| 除外 リスト に 追加 する ファイル を 選択
Error in line 4
Clear Usage Data||| 利用 履歴 データ を クリア
  log_e likelihood: 0
  log_2 likelihood: 0
     cross entropy: -nan
        perplexity: -nan
      posterior p0: -nan
 posterior al-feat: -nan
       size counts: 4
  1  model al-feat: -nan (tension=4)
  2  model al-feat: -nan (tension=-nan)
  3  model al-feat: -nan (tension=-nan)
  4  model al-feat: -nan (tension=-nan)
  5  model al-feat: -nan (tension=-nan)
  6  model al-feat: -nan (tension=-nan)
  7  model al-feat: -nan (tension=-nan)
  8  model al-feat: -nan (tension=-nan)
     final tension: -nan
ITERATION 3
Error in line 4
Clear Usage Data||| 利用 履歴 データ を クリア
Error in line 4
Delete records of which files and applications were used:||| ファイル と アプリケーション を 利用 し た 記録 の 削除 :
Error in line 4
In the past hour||| 1 時間 以内
Error in line 4
Select a file to blacklist||| 除外 リスト に 追加 する ファイル を 選択
  log_e likelihood: 0
  log_2 likelihood: 0
     cross entropy: -nan
        perplexity: -nan
      posterior p0: -nan
 posterior al-feat: -nan
       size counts: 4
  1  model al-feat: -nan (tension=-nan)
  2  model al-feat: -nan (tension=-nan)
  3  model al-feat: -nan (tension=-nan)
  4  model al-feat: -nan (tension=-nan)
  5  model al-feat: -nan (tension=-nan)
  6  model al-feat: -nan (tension=-nan)
  7  model al-feat: -nan (tension=-nan)
  8  model al-feat: -nan (tension=-nan)
     final tension: -nan
ITERATION 4
Error in line 4
Select a file to blacklist||| 除外 リスト に 追加 する ファイル を 選択
Error in line 4
Clear Usage Data||| 利用 履歴 データ を クリア
Error in line 4
In the past hour||| 1 時間 以内
Error in line 4
Delete records of which files and applications were used:||| ファイル と アプリケーション を 利用 し た 記録 の 削除 :
  log_e likelihood: 0
  log_2 likelihood: 0
     cross entropy: -nan
        perplexity: -nan
      posterior p0: -nan
 posterior al-feat: -nan
       size counts: 4
  1  model al-feat: -nan (tension=-nan)
  2  model al-feat: -nan (tension=-nan)
  3  model al-feat: -nan (tension=-nan)
  4  model al-feat: -nan (tension=-nan)
  5  model al-feat: -nan (tension=-nan)
  6  model al-feat: -nan (tension=-nan)
  7  model al-feat: -nan (tension=-nan)
  8  model al-feat: -nan (tension=-nan)
     final tension: -nan
ITERATION 5 (FINAL)
Error in line 4
In the past hour||| 1 時間 以内
Error in line 4
Delete records of which files and applications were used:||| ファイル と アプリケーション を 利用 し た 記録 の 削除 :
Error in line 4
Clear Usage Data||| 利用 履歴 データ を クリア
Error in line 4
Select a file to blacklist||| 除外 リスト に 追加 する ファイル を 選択
  log_e likelihood: 0
  log_2 likelihood: 0
     cross entropy: -nan
        perplexity: -nan
      posterior p0: -nan
 posterior al-feat: -nan
       size counts: 4
`

I've tried to align the file with and without spaces on the japanese sentences.

Thanks for the amazing free tool :-) 

Best, José

**Comment by redpony** [comment]
It looks like you’re missing a space between the last English word and the
||| separator word. This is required.

**Comment by ZordoC** [comment]
Yeah that was it!

For the interested :
 -You need to insert spaces in the japanese text otherwise the whole segment is treated as a token! The easiest tool I found is a python package called nagisa
