### ISSUE TITLE
Getting phrase tables from fast_align outputs

### ISSUE THREAD

**Issue by alvations** [clab/fast_align#7]
Thanks for the amazingly fast alignment tool, I understand that fast_align gives forward and backwards word alignments. 
1. How do we do grow-diag-final-and on the forward an backwards output? 
2. How do we get phrase tables from the outputs?

A short tutorial-like answer to the 2 questions would help a lot for users to use fast_align in the MT toolkit pipelines.

**Comment by alwayshjia** [comment]
> Use `phrase_based.py` from `Eliezer` : https://github.com/alvations/Eliezer/blob/master/eli/align/phrase_based.py

@alvations Hi, the link you mentioned here doesn't exist now. Could you provide the code of `phrase_based.py` please?

**Comment by alvations** [comment]
Try this https://github.com/alvations/Eliezer/blob/89c2858c5f058360a583be53577eede955ae852c/eli/align/phrase_based.py there is also a version from nltk at https://www.nltk.org/_modules/nltk/translate/phrase_based.html
